FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
EXPOSE 7096
EXPOSE 5087
WORKDIR /app

#build application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish --no-restore -c Release -o /app "CollegeManagementSystem.csproj"

# final image
FROM base AS final
COPY --from=build /app .
ENTRYPOINT ["dotnet", "CollegeManagementSystem.dll"]